language: ruby
rvm:
  - 2.2.2
cache: bundler
sudo: false
script:
  - bundle exec rake db:schema:load
  - bundle exec rspec
before_script:
  - psql -c 'create database fantassist_test' -U postgres
before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
